"""Render the six pinned Phosphor duotone SVGs into LVGL RGB565A8 assets.

Requires PySide6. This script is only needed when regenerating the assets;
the firmware build uses the checked-in C file and works offline.
"""

from pathlib import Path
from urllib.request import urlopen

from PySide6.QtCore import QByteArray, QRectF, Qt
from PySide6.QtGui import QImage, QPainter
from PySide6.QtSvg import QSvgRenderer


SOURCE_COMMIT = "2b75f3ad12b420c9504ef05df8d2564a28f8500e"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "main" / "ui" / "app_icons.c"
SIZE = 30
ICONS = (
    ("ai", "robot", "#ac93ff"),
    ("weather", "cloud-sun", "#ffca78"),
    ("wifi", "wifi-high", "#83c7ff"),
    ("calendar", "calendar-dots", "#83dfb6"),
    ("alarm", "alarm", "#ff9eb6"),
    ("music", "music-notes", "#87d8ed"),
)


def render_icon(name: str, color: str) -> QImage:
    url = (
        "https://raw.githubusercontent.com/phosphor-icons/core/"
        f"{SOURCE_COMMIT}/assets/duotone/{name}-duotone.svg"
    )
    with urlopen(url, timeout=20) as response:
        svg = response.read().decode("utf-8").replace("currentColor", color)
    renderer = QSvgRenderer(QByteArray(svg.encode("utf-8")))
    if not renderer.isValid():
        raise ValueError(f"Invalid SVG: {name}")

    high_res = QImage(SIZE * 4, SIZE * 4, QImage.Format_ARGB32)
    high_res.fill(Qt.transparent)
    painter = QPainter(high_res)
    painter.setRenderHint(QPainter.Antialiasing)
    renderer.render(painter, QRectF(0, 0, high_res.width(), high_res.height()))
    painter.end()
    return high_res.scaled(SIZE, SIZE, Qt.IgnoreAspectRatio, Qt.SmoothTransformation)


def rgb565a8(image: QImage) -> bytes:
    pixels = bytearray()
    alpha = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            color = image.pixelColor(x, y)
            value = ((color.red() >> 3) << 11) | ((color.green() >> 2) << 5) | (color.blue() >> 3)
            pixels.extend((value & 0xFF, value >> 8))
            alpha.append(color.alpha())
    return bytes(pixels + alpha)


def emit_array(name: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16])
        lines.append(f"    {row},")
    return (
        f"static const uint8_t app_icon_{name}_map[] = {{\n"
        + "\n".join(lines)
        + "\n};\n\n"
        + f"const lv_image_dsc_t app_icon_{name} = {{\n"
        + "    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        + "    .header.cf = LV_COLOR_FORMAT_RGB565A8,\n"
        + f"    .header.w = {SIZE},\n"
        + f"    .header.h = {SIZE},\n"
        + f"    .data_size = sizeof(app_icon_{name}_map),\n"
        + f"    .data = app_icon_{name}_map,\n"
        + "};\n"
    )


def main() -> None:
    parts = [
        "/* Phosphor Icons (MIT), pinned source commit: " + SOURCE_COMMIT + "\n"
        " * License: main/ui/PHOSPHOR_LICENSE.txt\n"
        " * Generated by tools/generate_app_icons.py; do not edit manually. */\n",
        '#include "app_icons.h"\n',
    ]
    for symbol, source_name, color in ICONS:
        parts.append(emit_array(symbol, rgb565a8(render_icon(source_name, color))))
    OUTPUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT} ({len(ICONS)} icons, {SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
